# Stage 1: Build the React application
FROM node:latest as build-stage
WORKDIR /app

# Copy and install frontend dependencies
COPY frontend/package*.json ./
RUN npm install

# Copy the frontend source code
COPY frontend/ .

# Build the frontend static files
RUN npm run build

# Stage 2: Serve the frontend static files with Nginx
FROM nginx:alpine
COPY --from=build-stage /app/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
