# Use the official MySQL image as the base image
FROM mysql:5.7

# Set environment variables correctly
ENV MYSQL_ROOT_PASSWORD=password \
    MYSQL_DATABASE=shms_db \
    MYSQL_USER=shms_admin \
    MYSQL_PASSWORD=shms_password

# Add the SQL scripts for initializing your database
ADD init.sql /docker-entrypoint-initdb.d
ADD populate.sql /docker-entrypoint-initdb.d

# Expose port 3306 for database connections
EXPOSE 3306
