apiVersion: v1
kind: Service
metadata:
  name: shms-backend
  namespace: webuiv2
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
  selector:
    app: shms-backend
