apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  namespace: sqlserv
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: ighost007/custom-mysql:latest
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "shms_password"
        - name: MYSQL_DATABASE
          value: "shms_database"
        - name: MYSQL_USER
          value: "shms_user"
        - name: MYSQL_PASSWORD
          value: "shms_password"
        volumeMounts:
        - name: mysql-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
