apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  namespace: mysql-space   
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mysql-space
  template:
    metadata:
      labels:
        app: mysql-space
    spec:
      containers:
      - name: myapp-container
        image: swelb/swelb:latest
        ports:
        - containerPort: 3306
