apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: your-registry/api:latest  # Update with your image path
        ports:
        - containerPort: 5000
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: password
        - name: MYSQL_DATABASE
          value: shms_database
        - name: MYSQL_USER
          value: shms_user
        - name: MYSQL_PASSWORD
          value: shms_password
