apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-service
  labels:
    app: api-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-service
  template:
    metadata:
      labels:
        app: api-service
    spec:
      containers:
      - name: api-service
        image: ighost007/smart-home-api:latest
        ports:
        - containerPort: 5000
        env:
        - name: DB_HOST
          value: "shms-database-service"
        - name: DB_PORT
          value: "3306"
        - name: DB_USER
          value: "shms_user"
        - name: DB_PASSWORD
          value: "shms_password"
        - name: DB_NAME
          value: "shms_database"

---
apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  selector:
    app: api-service
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
