# Use the official Python 3.9 image from Docker Hub
FROM python:3.9

# Set the working directory in the container
WORKDIR /app

# Copy the Python application and requirements file into the container
COPY app.py /app/
COPY requirements.txt /app/

# Install any dependencies
RUN pip install -r requirements.txt

# Expose the Flask port
EXPOSE 5000

# Run the Flask application
CMD ["python", "app.py"]
