apiVersion: v1
kind: Service
metadata:
  name: fastapi-service
  namespace: webuiv2
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 5000
    protocol: TCP
  selector:
    app: fastapi-service
